channels:
- conda-forge
dependencies:
- python=3.9.22
- pip<=25.1.1
- pip:
  - mlflow==2.22.0
  - numpy==1.23.5
  - pandas==2.2.3
  - scipy==1.13.1
  - statsmodels==0.14.4
name: mlflow-env
